### ISSUE TITLE
Intermittent failures downloading large files

### ISSUE THREAD

**Issue by ghost** [JFrogDev/artifactory-cli-go#7] opened 2015-12-08 15:31 UTC
Hi
I've been seeing an intermittent error using artifactory-cli-go (v1.2.0) to fetch from Artifactory.

This seems to be the significant part of the log:

```
[Thread 2] Downloading https://repo.example.com/com.example.testing/com/example/firmware/build/build-toolchain-arm/1.0-SNAPSHOT/build-toolchain-arm-1.0-20151207.204922-1.tar.gz
[Thread 0] Downloading https://repo.example.com/com.example.testing/com/example/firmware/build/build-toolchain-arm/1.0-SNAPSHOT/build-toolchain-arm-1.0-20151207.204922-1-log.txt
[Thread 1] Downloading https://repo.example.com/com.example.testing/com/example/firmware/build/build-toolchain-arm/1.0-SNAPSHOT/build-toolchain-arm-1.0-20151207.204922-1.pom
[Thread 1] Artifactory response: 200 OK
[Thread 0] [2]: 206 Partial Content...
[Thread 0] [1]: 206 Partial Content...
[Thread 2] [1]: 206 Partial Content...
[Thread 0] [0]: 206 Partial Content...
panic: open /tmp/artifactory.cli.588660923/com/example/firmware/build/build-toolchain-arm/1.0-SNAPSHOT/build-toolchain-arm-1.0-20151207.204922-1-log.txt_0: no such file or directory

goroutine 3 [running]:
github.com/JFrogDev/artifactory-cli-go/utils.CheckError(0x7f57a1221878, 0xc8204920c0)
    /home/shared/baserock/gopath/src/github.com/JFrogDev/artifactory-cli-go/utils/utils.go:25 +0x4b
github.com/JFrogDev/artifactory-cli-go/utils.AppendFile(0xc82024e160, 0xa1, 0xc8200f8040)
    /home/shared/baserock/gopath/src/github.com/JFrogDev/artifactory-cli-go/utils/ioUtils.go:199 +0x81
github.com/JFrogDev/artifactory-cli-go/utils.DownloadFileConcurrently(0xc8200cf440, 0xba, 0xc82015c050, 0x47, 0xc82000a3c0, 0x38, 0xc8203ca6c0, 0xa, 0x1bfd9b6, 0xc820072120)
    /home/shared/baserock/gopath/src/github.com/JFrogDev/artifactory-cli-go/utils/artifactoryUtils.go:125 +0x54c
github.com/JFrogDev/artifactory-cli-go/commands.downloadFile(0xc8200cf440, 0xba, 0xc82015c050, 0x47, 0xc82000a3c0, 0x38, 0xc8203ca6c0, 0xa, 0xc820072120)
    /home/shared/baserock/gopath/src/github.com/JFrogDev/artifactory-cli-go/commands/download.go:60 +0x233
github.com/JFrogDev/artifactory-cli-go/commands.downloadFiles.func1(0x3, 0xc820072120, 0xc8203e8000, 0x3, 0x4, 0xc8200107f0, 0x0)
    /home/shared/baserock/gopath/src/github.com/JFrogDev/artifactory-cli-go/commands/download.go:42 +0x445
created by github.com/JFrogDev/artifactory-cli-go/commands.downloadFiles
    /home/shared/baserock/gopath/src/github.com/JFrogDev/artifactory-cli-go/commands/download.go:46 +0xcf
```

The full log is attached.

I seem to be able to work around this by passing `--split-count=0`. I can't spot any obvious cause in the DownloadFileConcurrently() code.

Sam

**Comment by ghost** [comment] 2015-12-08 15:34
[artifactory-cli-go.panic-bug.txt](https://github.com/JFrogDev/artifactory-cli-go/files/55635/artifactory-cli-go.panic-bug.txt)

**Comment by eyalbe4** [comment] 2015-12-08 18:17
Thanks for reporting this @ssssam
After many attempts I finally managed to replicate the issue. I'll update soon.

**Comment by eyalbe4** [comment] 2015-12-09 10:11
@ssssam, I've just committed a fix for this issue and we will soon release a new version to Bintray.
If you're able to build the tool manually before the release and confirm that the issue is resolved for you - it would be great.
Thanks again for reporting this!

**Comment by ghost** [comment] 2015-12-09 16:16
I've built the new version and I can't reproduce the issue (in 25 tries).

That said, I tried with the old version and the today issue didn't occur ... I guess the phase of the moon has changed :)

Thanks for fixing this, I'm glad you could reproduce it !

**Comment by eyalbe4** [comment] 2015-12-09 16:22
Anytime @ssssam :)

**Comment by eyalbe4** [comment] 2015-12-20 16:48
Version 1.2.1 is released and includes this fix.

**Closed as completed by eyalbe4** 2015-12-20 16:48 UTC
